// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gzipcMulticoreStreaming_lzBooster_255_4096_16384_64_38_Pipeline_lz_booster (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        compressedStream1_dout,
        compressedStream1_num_data_valid,
        compressedStream1_fifo_cap,
        compressedStream1_empty_n,
        compressedStream1_read,
        lclBufStream_dout,
        lclBufStream_empty_n,
        lclBufStream_read,
        lclBufStream_din,
        lclBufStream_full_n,
        lclBufStream_write,
        boosterStream_din,
        boosterStream_num_data_valid,
        boosterStream_fifo_cap,
        boosterStream_full_n,
        boosterStream_write,
        tmp_data_V_37_reload,
        trunc_ln,
        outValue_V,
        outValue_V_8_out,
        outValue_V_8_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [32:0] compressedStream1_dout;
input  [2:0] compressedStream1_num_data_valid;
input  [2:0] compressedStream1_fifo_cap;
input   compressedStream1_empty_n;
output   compressedStream1_read;
input  [31:0] lclBufStream_dout;
input   lclBufStream_empty_n;
output   lclBufStream_read;
output  [31:0] lclBufStream_din;
input   lclBufStream_full_n;
output   lclBufStream_write;
output  [32:0] boosterStream_din;
input  [2:0] boosterStream_num_data_valid;
input  [2:0] boosterStream_fifo_cap;
input   boosterStream_full_n;
output   boosterStream_write;
input  [31:0] tmp_data_V_37_reload;
input  [0:0] trunc_ln;
input  [31:0] outValue_V;
output  [31:0] outValue_V_8_out;
output   outValue_V_8_out_ap_vld;

reg ap_idle;
reg compressedStream1_read;
reg lclBufStream_read;
reg lclBufStream_write;
reg boosterStream_write;
reg outValue_V_8_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] nextVal_strobe_V_reg_228;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg   [0:0] nextVal_strobe_V_reg_228_pp0_iter3_reg;
reg   [0:0] icmp_ln496_reg_797;
reg   [0:0] and_ln498_2_reg_806;
reg   [0:0] outFlag_reg_810;
reg    ap_predicate_op124_write_state5;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    lclBufStream_i_blk_n;
wire    ap_block_pp0_stage0;
reg    lclBufStream_o_blk_n;
reg    compressedStream1_blk_n;
reg    boosterStream_blk_n;
reg   [0:0] nextVal_strobe_V_reg_228_pp0_iter1_reg;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] nextVal_strobe_V_reg_228_pp0_iter2_reg;
wire   [31:0] tmp_data_V_56_fu_317_p1;
reg   [31:0] tmp_data_V_56_reg_750;
reg   [0:0] tmp_reg_755;
reg   [31:0] outValue_V_5_reg_760;
reg   [31:0] outValue_V_5_reg_760_pp0_iter2_reg;
reg   [31:0] outValue_V_5_reg_760_pp0_iter3_reg;
wire   [7:0] tCh_fu_333_p1;
reg   [7:0] tCh_reg_767;
reg   [7:0] tCh_reg_767_pp0_iter2_reg;
reg   [7:0] tLen_reg_773;
reg   [7:0] tLen_reg_773_pp0_iter2_reg;
reg   [15:0] tOffset_reg_779;
reg   [15:0] tOffset_reg_779_pp0_iter2_reg;
wire   [0:0] boostFlag_fu_367_p2;
reg   [0:0] boostFlag_reg_784;
reg   [0:0] boostFlag_reg_784_pp0_iter2_reg;
reg   [31:0] iIdx_13_reg_791;
wire   [0:0] icmp_ln496_fu_413_p2;
wire   [0:0] and_ln498_2_fu_461_p2;
wire   [0:0] outFlag_fu_476_p2;
wire   [0:0] icmp_ln508_fu_481_p2;
reg   [0:0] icmp_ln508_reg_814;
wire   [7:0] trunc_ln499_fu_578_p1;
reg   [7:0] trunc_ln499_reg_823;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [11:0] local_mem_address0;
reg    local_mem_ce0;
reg    local_mem_we0;
reg   [11:0] local_mem_address1;
reg    local_mem_ce1;
wire   [7:0] local_mem_q1;
wire    ap_loop_init;
reg   [8:0] ap_phi_mux_skip_len_418_phi_fu_242_p4;
wire  signed [8:0] skip_len_9_fu_500_p3;
wire   [8:0] ap_phi_reg_pp0_iter3_skip_len_418_reg_239;
reg   [0:0] ap_phi_mux_matchFlag_412_phi_fu_252_p4;
wire   [0:0] ap_phi_reg_pp0_iter3_matchFlag_412_reg_249;
reg   [7:0] ap_phi_mux_empty_phi_fu_262_p10;
wire   [7:0] ap_phi_reg_pp0_iter4_empty_reg_259;
wire   [63:0] zext_ln493_fu_390_p1;
wire   [63:0] zext_ln520_fu_425_p1;
wire   [63:0] zext_ln520_4_fu_486_p1;
wire   [63:0] zext_ln520_3_fu_600_p1;
reg   [7:0] match_ch_fu_104;
reg   [7:0] ap_sig_allocacmp_match_ch_load;
reg   [15:0] skip_len_fu_108;
wire   [15:0] skip_len_7_fu_419_p2;
wire  signed [15:0] sext_ln449_fu_508_p1;
wire  signed [15:0] sext_ln174_fu_551_p1;
reg   [31:0] iIdx_fu_112;
wire   [31:0] iIdx_14_fu_380_p2;
reg   [31:0] tmp_data_V_fu_116;
reg   [31:0] match_loc_fu_120;
wire   [31:0] match_loc_8_fu_467_p2;
wire   [31:0] match_loc_7_fu_588_p2;
reg   [31:0] match_len_fu_124;
wire   [31:0] match_len_6_fu_582_p2;
reg   [0:0] matchFlag_fu_128;
reg   [31:0] outStreamValue_data_V_fu_132;
wire   [31:0] p_Result_s_fu_651_p5;
reg    ap_block_pp0_stage0_01001;
wire   [3:0] tmp_204_fu_357_p4;
wire   [11:0] empty_241_fu_386_p1;
wire   [11:0] empty_240_fu_406_p1;
wire   [0:0] icmp_ln498_fu_444_p2;
wire   [0:0] and_ln498_fu_455_p2;
wire   [0:0] icmp_ln498_2_fu_450_p2;
wire   [31:0] zext_ln487_fu_410_p1;
wire   [11:0] trunc_ln441_fu_472_p1;
wire   [8:0] zext_ln514_fu_491_p1;
wire   [8:0] skip_len_8_fu_494_p2;
wire   [11:0] add_ln441_fu_594_p2;
wire   [7:0] add_ln392_fu_646_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_51;
reg    ap_enable_state3_pp0_iter2_stage0;
reg    ap_predicate_op64_load_state4;
reg    ap_enable_operation_64;
reg    ap_enable_state4_pp0_iter3_stage0;
reg    ap_predicate_op115_load_state5;
reg    ap_enable_operation_115;
reg    ap_enable_state5_pp0_iter4_stage0;
reg    ap_predicate_op80_load_state4;
reg    ap_enable_operation_80;
reg    ap_predicate_op117_load_state5;
reg    ap_enable_operation_117;
reg    ap_predicate_op110_load_state4;
reg    ap_enable_operation_110;
reg    ap_predicate_op130_load_state5;
reg    ap_enable_operation_130;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_349;
reg    ap_condition_628;
reg    ap_condition_357;
reg    ap_condition_638;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

gzipcMulticoreStreaming_lzBooster_255_4096_16384_64_Pipeline_lz_booster_local_mem_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
local_mem_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_mem_address0),
    .ce0(local_mem_ce0),
    .we0(local_mem_we0),
    .d0(tCh_reg_767),
    .address1(local_mem_address1),
    .ce1(local_mem_ce1),
    .q1(local_mem_q1)
);

gzipcMulticoreStreaming_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            iIdx_fu_112 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (nextVal_strobe_V_reg_228_pp0_iter1_reg == 1'd1))) begin
            iIdx_fu_112 <= iIdx_14_fu_380_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        matchFlag_fu_128 <= 1'd1;
    end else if (((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (outFlag_fu_476_p2 == 1'd1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        matchFlag_fu_128 <= ap_phi_mux_matchFlag_412_phi_fu_252_p4;
    end else if ((((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln508_fu_481_p2 == 1'd1) & (outFlag_fu_476_p2 == 1'd0) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        matchFlag_fu_128 <= 1'd0;
    end else if (((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln508_fu_481_p2 == 1'd0) & (outFlag_fu_476_p2 == 1'd0) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        matchFlag_fu_128 <= boostFlag_reg_784_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        match_len_fu_124 <= 32'd0;
    end else if (((1'd1 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        match_len_fu_124 <= match_len_6_fu_582_p2;
    end else if ((((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln508_fu_481_p2 == 1'd1) & (outFlag_fu_476_p2 == 1'd0) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (outFlag_fu_476_p2 == 1'd1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln508_fu_481_p2 == 1'd0) & (outFlag_fu_476_p2 == 1'd0) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        match_len_fu_124 <= 32'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        match_loc_fu_120 <= 32'd0;
    end else if (((1'd1 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        match_loc_fu_120 <= match_loc_7_fu_588_p2;
    end else if ((((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln508_fu_481_p2 == 1'd1) & (outFlag_fu_476_p2 == 1'd0) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (outFlag_fu_476_p2 == 1'd1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln508_fu_481_p2 == 1'd0) & (outFlag_fu_476_p2 == 1'd0) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        match_loc_fu_120 <= match_loc_8_fu_467_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_638)) begin
            nextVal_strobe_V_reg_228 <= tmp_reg_755;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            nextVal_strobe_V_reg_228 <= trunc_ln;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outStreamValue_data_V_fu_132 <= outValue_V;
    end else if (((icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1) & (1'd1 == and_ln498_2_reg_806) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outStreamValue_data_V_fu_132 <= p_Result_s_fu_651_p5;
    end else if ((((outFlag_reg_810 == 1'd1) & (1'd0 == and_ln498_2_reg_806) & (icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((outFlag_reg_810 == 1'd0) & (1'd0 == and_ln498_2_reg_806) & (icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln508_reg_814 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((outFlag_reg_810 == 1'd0) & (1'd0 == and_ln498_2_reg_806) & (icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln508_reg_814 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        outStreamValue_data_V_fu_132 <= outValue_V_5_reg_760_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (outFlag_fu_476_p2 == 1'd1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        skip_len_fu_108 <= sext_ln174_fu_551_p1;
    end else if ((((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd1 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln508_fu_481_p2 == 1'd1) & (outFlag_fu_476_p2 == 1'd0) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        skip_len_fu_108 <= 16'd0;
    end else if (((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln508_fu_481_p2 == 1'd0) & (outFlag_fu_476_p2 == 1'd0) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        skip_len_fu_108 <= sext_ln449_fu_508_p1;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln496_fu_413_p2 == 1'd0) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        skip_len_fu_108 <= skip_len_7_fu_419_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            tmp_data_V_fu_116 <= tmp_data_V_37_reload;
        end else if (((nextVal_strobe_V_reg_228 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            tmp_data_V_fu_116 <= tmp_data_V_56_reg_750;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln496_fu_413_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln498_2_reg_806 <= and_ln498_2_fu_461_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        nextVal_strobe_V_reg_228_pp0_iter1_reg <= nextVal_strobe_V_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        boostFlag_reg_784_pp0_iter2_reg <= boostFlag_reg_784;
        iIdx_13_reg_791 <= iIdx_fu_112;
        nextVal_strobe_V_reg_228_pp0_iter2_reg <= nextVal_strobe_V_reg_228_pp0_iter1_reg;
        nextVal_strobe_V_reg_228_pp0_iter3_reg <= nextVal_strobe_V_reg_228_pp0_iter2_reg;
        outValue_V_5_reg_760_pp0_iter2_reg <= outValue_V_5_reg_760;
        outValue_V_5_reg_760_pp0_iter3_reg <= outValue_V_5_reg_760_pp0_iter2_reg;
        tCh_reg_767_pp0_iter2_reg <= tCh_reg_767;
        tLen_reg_773_pp0_iter2_reg <= tLen_reg_773;
        tOffset_reg_779_pp0_iter2_reg <= tOffset_reg_779;
    end
end

always @ (posedge ap_clk) begin
    if (((nextVal_strobe_V_reg_228 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        boostFlag_reg_784 <= boostFlag_fu_367_p2;
        outValue_V_5_reg_760 <= lclBufStream_dout;
        tCh_reg_767 <= tCh_fu_333_p1;
        tLen_reg_773 <= {{lclBufStream_dout[15:8]}};
        tOffset_reg_779 <= {{lclBufStream_dout[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln496_reg_797 <= icmp_ln496_fu_413_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln498_2_fu_461_p2) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln508_reg_814 <= icmp_ln508_fu_481_p2;
        outFlag_reg_810 <= outFlag_fu_476_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        match_ch_fu_104 <= ap_phi_mux_empty_phi_fu_262_p10;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_V_56_reg_750 <= tmp_data_V_56_fu_317_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_reg_755 <= compressedStream1_dout[32'd32];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln498_2_fu_461_p2) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln499_reg_823 <= trunc_ln499_fu_578_p1;
    end
end

always @ (*) begin
    if (((ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (nextVal_strobe_V_reg_228_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((outFlag_reg_810 == 1'd1) & (1'd0 == and_ln498_2_reg_806) & (icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1)) | ((icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1) & (1'd1 == and_ln498_2_reg_806)) | ((outFlag_reg_810 == 1'd0) & (1'd0 == and_ln498_2_reg_806) & (icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1) & (icmp_ln508_reg_814 == 1'd1)) | ((outFlag_reg_810 == 1'd0) & (1'd0 == and_ln498_2_reg_806) & (icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1) & (icmp_ln508_reg_814 == 1'd0)) | ((icmp_ln496_reg_797 == 1'd0) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1)))) begin
        ap_phi_mux_empty_phi_fu_262_p10 = local_mem_q1;
    end else begin
        ap_phi_mux_empty_phi_fu_262_p10 = ap_phi_reg_pp0_iter4_empty_reg_259;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_349)) begin
        if ((icmp_ln508_fu_481_p2 == 1'd1)) begin
            ap_phi_mux_matchFlag_412_phi_fu_252_p4 = 1'd0;
        end else if ((icmp_ln508_fu_481_p2 == 1'd0)) begin
            ap_phi_mux_matchFlag_412_phi_fu_252_p4 = boostFlag_reg_784_pp0_iter2_reg;
        end else begin
            ap_phi_mux_matchFlag_412_phi_fu_252_p4 = ap_phi_reg_pp0_iter3_matchFlag_412_reg_249;
        end
    end else begin
        ap_phi_mux_matchFlag_412_phi_fu_252_p4 = ap_phi_reg_pp0_iter3_matchFlag_412_reg_249;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_628)) begin
            ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 = tmp_reg_755;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 = trunc_ln;
        end else begin
            ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 = tmp_reg_755;
        end
    end else begin
        ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 = tmp_reg_755;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_349)) begin
        if ((icmp_ln508_fu_481_p2 == 1'd1)) begin
            ap_phi_mux_skip_len_418_phi_fu_242_p4 = 9'd0;
        end else if ((icmp_ln508_fu_481_p2 == 1'd0)) begin
            ap_phi_mux_skip_len_418_phi_fu_242_p4 = skip_len_9_fu_500_p3;
        end else begin
            ap_phi_mux_skip_len_418_phi_fu_242_p4 = ap_phi_reg_pp0_iter3_skip_len_418_reg_239;
        end
    end else begin
        ap_phi_mux_skip_len_418_phi_fu_242_p4 = ap_phi_reg_pp0_iter3_skip_len_418_reg_239;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_match_ch_load = ap_phi_mux_empty_phi_fu_262_p10;
    end else begin
        ap_sig_allocacmp_match_ch_load = match_ch_fu_104;
    end
end

always @ (*) begin
    if (((ap_predicate_op124_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        boosterStream_blk_n = boosterStream_full_n;
    end else begin
        boosterStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op124_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        boosterStream_write = 1'b1;
    end else begin
        boosterStream_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        compressedStream1_blk_n = compressedStream1_empty_n;
    end else begin
        compressedStream1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        compressedStream1_read = 1'b1;
    end else begin
        compressedStream1_read = 1'b0;
    end
end

always @ (*) begin
    if (((nextVal_strobe_V_reg_228 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        lclBufStream_i_blk_n = lclBufStream_empty_n;
    end else begin
        lclBufStream_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((nextVal_strobe_V_reg_228 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        lclBufStream_o_blk_n = lclBufStream_full_n;
    end else begin
        lclBufStream_o_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((nextVal_strobe_V_reg_228 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        lclBufStream_read = 1'b1;
    end else begin
        lclBufStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((nextVal_strobe_V_reg_228 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        lclBufStream_write = 1'b1;
    end else begin
        lclBufStream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_357)) begin
        if (((1'd1 == and_ln498_2_fu_461_p2) & (icmp_ln496_fu_413_p2 == 1'd1))) begin
            local_mem_address1 = zext_ln520_3_fu_600_p1;
        end else if (((1'd0 == and_ln498_2_fu_461_p2) & (icmp_ln496_fu_413_p2 == 1'd1))) begin
            local_mem_address1 = zext_ln520_4_fu_486_p1;
        end else if ((icmp_ln496_fu_413_p2 == 1'd0)) begin
            local_mem_address1 = zext_ln520_fu_425_p1;
        end else begin
            local_mem_address1 = 'bx;
        end
    end else begin
        local_mem_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_mem_ce0 = 1'b1;
    end else begin
        local_mem_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln496_fu_413_p2 == 1'd0) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd1 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd0 == and_ln498_2_fu_461_p2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        local_mem_ce1 = 1'b1;
    end else begin
        local_mem_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (nextVal_strobe_V_reg_228_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_mem_we0 = 1'b1;
    end else begin
        local_mem_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outValue_V_8_out_ap_vld = 1'b1;
    end else begin
        outValue_V_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln392_fu_646_p2 = (trunc_ln499_reg_823 + 8'd1);

assign add_ln441_fu_594_p2 = (empty_240_fu_406_p1 + 12'd1);

assign and_ln498_2_fu_461_p2 = (icmp_ln498_2_fu_450_p2 & and_ln498_fu_455_p2);

assign and_ln498_fu_455_p2 = (matchFlag_fu_128 & icmp_ln498_fu_444_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_predicate_op124_write_state5 == 1'b1) & (boosterStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((lclBufStream_full_n == 1'b0) & (nextVal_strobe_V_reg_228 == 1'd1)) | ((nextVal_strobe_V_reg_228 == 1'd1) & (lclBufStream_empty_n == 1'b0)))) | ((ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 == 1'd1) & (compressedStream1_empty_n == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_predicate_op124_write_state5 == 1'b1) & (boosterStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((lclBufStream_full_n == 1'b0) & (nextVal_strobe_V_reg_228 == 1'd1)) | ((nextVal_strobe_V_reg_228 == 1'd1) & (lclBufStream_empty_n == 1'b0)))) | ((ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 == 1'd1) & (compressedStream1_empty_n == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_predicate_op124_write_state5 == 1'b1) & (boosterStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((lclBufStream_full_n == 1'b0) & (nextVal_strobe_V_reg_228 == 1'd1)) | ((nextVal_strobe_V_reg_228 == 1'd1) & (lclBufStream_empty_n == 1'b0)))) | ((ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 == 1'd1) & (compressedStream1_empty_n == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_phi_mux_nextVal_strobe_V_phi_fu_231_p4 == 1'd1) & (compressedStream1_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((lclBufStream_full_n == 1'b0) & (nextVal_strobe_V_reg_228 == 1'd1)) | ((nextVal_strobe_V_reg_228 == 1'd1) & (lclBufStream_empty_n == 1'b0)));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((ap_predicate_op124_write_state5 == 1'b1) & (boosterStream_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_349 = ((1'd0 == and_ln498_2_fu_461_p2) & (outFlag_fu_476_p2 == 1'd1) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1));
end

always @ (*) begin
    ap_condition_357 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_628 = ((nextVal_strobe_V_reg_228 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_638 = ((nextVal_strobe_V_reg_228 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_enable_operation_110 = (ap_predicate_op110_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_115 = (ap_predicate_op115_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_117 = (ap_predicate_op117_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_130 = (ap_predicate_op130_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_51 = (nextVal_strobe_V_reg_228_pp0_iter1_reg == 1'd1);
end

always @ (*) begin
    ap_enable_operation_64 = (ap_predicate_op64_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_80 = (ap_predicate_op80_load_state4 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state4_pp0_iter3_stage0 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state5_pp0_iter4_stage0 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter3_matchFlag_412_reg_249 = 'bx;

assign ap_phi_reg_pp0_iter3_skip_len_418_reg_239 = 'bx;

assign ap_phi_reg_pp0_iter4_empty_reg_259 = 'bx;

always @ (*) begin
    ap_predicate_op110_load_state4 = ((1'd1 == and_ln498_2_fu_461_p2) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op115_load_state5 = ((icmp_ln496_reg_797 == 1'd0) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op117_load_state5 = ((1'd0 == and_ln498_2_reg_806) & (icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op124_write_state5 = ((outFlag_reg_810 == 1'd1) & (1'd0 == and_ln498_2_reg_806) & (icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op130_load_state5 = ((icmp_ln496_reg_797 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter3_reg == 1'd1) & (1'd1 == and_ln498_2_reg_806));
end

always @ (*) begin
    ap_predicate_op64_load_state4 = ((icmp_ln496_fu_413_p2 == 1'd0) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op80_load_state4 = ((1'd0 == and_ln498_2_fu_461_p2) & (icmp_ln496_fu_413_p2 == 1'd1) & (nextVal_strobe_V_reg_228_pp0_iter2_reg == 1'd1));
end

assign boostFlag_fu_367_p2 = ((tmp_204_fu_357_p4 == 4'd0) ? 1'b1 : 1'b0);

assign boosterStream_din = {{1'd1}, {outStreamValue_data_V_fu_132}};

assign empty_240_fu_406_p1 = match_loc_fu_120[11:0];

assign empty_241_fu_386_p1 = iIdx_fu_112[11:0];

assign iIdx_14_fu_380_p2 = (iIdx_fu_112 + 32'd1);

assign icmp_ln496_fu_413_p2 = ((skip_len_fu_108 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln498_2_fu_450_p2 = ((tCh_reg_767_pp0_iter2_reg == ap_sig_allocacmp_match_ch_load) ? 1'b1 : 1'b0);

assign icmp_ln498_fu_444_p2 = ((match_len_fu_124 < 32'd255) ? 1'b1 : 1'b0);

assign icmp_ln508_fu_481_p2 = ((tLen_reg_773_pp0_iter2_reg == 8'd0) ? 1'b1 : 1'b0);

assign lclBufStream_din = tmp_data_V_fu_116;

assign local_mem_address0 = zext_ln493_fu_390_p1;

assign match_len_6_fu_582_p2 = (match_len_fu_124 + 32'd1);

assign match_loc_7_fu_588_p2 = (match_loc_fu_120 + 32'd1);

assign match_loc_8_fu_467_p2 = (iIdx_13_reg_791 - zext_ln487_fu_410_p1);

assign outFlag_fu_476_p2 = ((iIdx_13_reg_791 != 32'd0) ? 1'b1 : 1'b0);

assign outValue_V_8_out = outStreamValue_data_V_fu_132;

assign p_Result_s_fu_651_p5 = {{outStreamValue_data_V_fu_132[31:16]}, {add_ln392_fu_646_p2}, {outStreamValue_data_V_fu_132[7:0]}};

assign sext_ln174_fu_551_p1 = $signed(ap_phi_mux_skip_len_418_phi_fu_242_p4);

assign sext_ln449_fu_508_p1 = skip_len_9_fu_500_p3;

assign skip_len_7_fu_419_p2 = ($signed(skip_len_fu_108) + $signed(16'd65535));

assign skip_len_8_fu_494_p2 = ($signed(zext_ln514_fu_491_p1) + $signed(9'd511));

assign skip_len_9_fu_500_p3 = ((boostFlag_reg_784_pp0_iter2_reg[0:0] == 1'b1) ? 9'd0 : skip_len_8_fu_494_p2);

assign tCh_fu_333_p1 = lclBufStream_dout[7:0];

assign tmp_204_fu_357_p4 = {{lclBufStream_dout[31:28]}};

assign tmp_data_V_56_fu_317_p1 = compressedStream1_dout[31:0];

assign trunc_ln441_fu_472_p1 = match_loc_8_fu_467_p2[11:0];

assign trunc_ln499_fu_578_p1 = match_len_fu_124[7:0];

assign zext_ln487_fu_410_p1 = tOffset_reg_779_pp0_iter2_reg;

assign zext_ln493_fu_390_p1 = empty_241_fu_386_p1;

assign zext_ln514_fu_491_p1 = tLen_reg_773_pp0_iter2_reg;

assign zext_ln520_3_fu_600_p1 = add_ln441_fu_594_p2;

assign zext_ln520_4_fu_486_p1 = trunc_ln441_fu_472_p1;

assign zext_ln520_fu_425_p1 = empty_240_fu_406_p1;

endmodule //gzipcMulticoreStreaming_lzBooster_255_4096_16384_64_38_Pipeline_lz_booster
