-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gzipcMulticoreStreaming_canonizeGetCodes_286_10_14_Pipeline_process_symbols is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    heapCanzStream_dout : IN STD_LOGIC_VECTOR (24 downto 0);
    heapCanzStream_num_data_valid : IN STD_LOGIC_VECTOR (11 downto 0);
    heapCanzStream_fifo_cap : IN STD_LOGIC_VECTOR (11 downto 0);
    heapCanzStream_empty_n : IN STD_LOGIC;
    heapCanzStream_read : OUT STD_LOGIC;
    zext_ln1385 : IN STD_LOGIC_VECTOR (8 downto 0);
    length_histogram_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    length_histogram_V_ce0 : OUT STD_LOGIC;
    length_histogram_V_q0 : IN STD_LOGIC_VECTOR (11 downto 0);
    symbol_bits_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    symbol_bits_V_ce0 : OUT STD_LOGIC;
    symbol_bits_V_we0 : OUT STD_LOGIC;
    symbol_bits_V_d0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of gzipcMulticoreStreaming_canonizeGetCodes_286_10_14_Pipeline_process_symbols is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_12 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal decLenHistFlag_reg_118 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln927_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal heapCanzStream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal updSymBitsFlag_reg_130 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln1385_cast_fu_245_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1385_cast_reg_403 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln927_reg_414 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln939_reg_418 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_decLenHistFlag_phi_fu_122_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln931_reg_427 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_phi_mux_decLenHistFlag_3_i256_phi_fu_198_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_updSymBitsFlag_phi_fu_134_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_updSymBitsFlag_3_i258_phi_fu_182_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_decLenHistFlag_3_i257_phi_fu_146_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_decLenHistFlag_3_i257_reg_142 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_decLenHistFlag_3_i257_reg_142 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_decLenHistFlag_3_i257_reg_142 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_count_i_3253_phi_fu_160_p6 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter0_count_i_3253_reg_157 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter1_count_i_3253_reg_157 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter2_count_i_3253_reg_157 : STD_LOGIC_VECTOR (9 downto 0);
    signal count_V_5_fu_331_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_mux_count_V_7_phi_fu_171_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal count_V_11_fu_361_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter2_count_V_7_reg_168 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_322_fu_340_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_updSymBitsFlag_3_i258_reg_178 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_decLenHistFlag_3_i256_reg_194 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_count_V_8_phi_fu_213_p6 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter2_count_V_8_reg_210 : STD_LOGIC_VECTOR (9 downto 0);
    signal count_V_10_fu_316_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln941_fu_281_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln932_fu_291_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_fu_356_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_0_0_0_0_0_0230_fu_56 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln145_fu_312_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_p_0_0_0_0_0_0230_load : STD_LOGIC_VECTOR (9 downto 0);
    signal k_fu_60 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_5_fu_301_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal length_fu_64 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_240_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal count_V_fu_68 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_count_V_4 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_227_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_357 : BOOLEAN;
    signal ap_condition_360 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component gzipcMulticoreStreaming_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component gzipcMulticoreStreaming_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_count_i_3253_reg_157_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_1) and (grp_fu_234_p2 = ap_const_lv1_1)) or ((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_0) and (grp_fu_234_p2 = ap_const_lv1_1)))) then 
                ap_phi_reg_pp0_iter2_count_i_3253_reg_157 <= ap_sig_allocacmp_count_V_4;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_count_i_3253_reg_157 <= ap_phi_reg_pp0_iter1_count_i_3253_reg_157;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_decLenHistFlag_3_i257_reg_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_1) and (grp_fu_234_p2 = ap_const_lv1_1)) or ((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_0) and (grp_fu_234_p2 = ap_const_lv1_1)))) then 
                ap_phi_reg_pp0_iter2_decLenHistFlag_3_i257_reg_142 <= ap_const_lv1_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_decLenHistFlag_3_i257_reg_142 <= ap_phi_reg_pp0_iter1_decLenHistFlag_3_i257_reg_142;
            end if; 
        end if;
    end process;

    count_V_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    count_V_fu_68 <= ap_const_lv10_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
                    count_V_fu_68 <= ap_phi_mux_count_V_8_phi_fu_213_p6;
                end if;
            end if; 
        end if;
    end process;

    decLenHistFlag_reg_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
                decLenHistFlag_reg_118 <= ap_phi_mux_decLenHistFlag_3_i256_phi_fu_198_p6;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                decLenHistFlag_reg_118 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    k_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_60 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_357)) then 
                    k_fu_60 <= k_5_fu_301_p2;
                end if;
            end if; 
        end if;
    end process;

    length_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                length_fu_64 <= ap_const_lv16_12;
            elsif ((((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_1) and (grp_fu_234_p2 = ap_const_lv1_0)) or ((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_0) and (grp_fu_234_p2 = ap_const_lv1_0)))) then 
                length_fu_64 <= grp_fu_240_p2;
            end if; 
        end if;
    end process;

    updSymBitsFlag_reg_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
                updSymBitsFlag_reg_130 <= ap_phi_mux_updSymBitsFlag_3_i258_phi_fu_182_p6;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                updSymBitsFlag_reg_130 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_count_i_3253_reg_157 <= ap_phi_reg_pp0_iter0_count_i_3253_reg_157;
                ap_phi_reg_pp0_iter1_decLenHistFlag_3_i257_reg_142 <= ap_phi_reg_pp0_iter0_decLenHistFlag_3_i257_reg_142;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln927_reg_414 <= icmp_ln927_fu_271_p2;
                    zext_ln1385_cast_reg_403(8 downto 0) <= zext_ln1385_cast_fu_245_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_1))) then
                or_ln931_reg_427 <= grp_fu_234_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_0))) then
                or_ln939_reg_418 <= grp_fu_234_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (decLenHistFlag_reg_118 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (or_ln939_reg_418 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (decLenHistFlag_reg_118 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (or_ln939_reg_418 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1)))) then
                p_0_0_0_0_0_0230_fu_56 <= trunc_ln145_fu_312_p1;
            end if;
        end if;
    end process;
    zext_ln1385_cast_reg_403(31 downto 9) <= "00000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, heapCanzStream_empty_n, decLenHistFlag_reg_118)
    begin
                ap_block_pp0_stage0_11001 <= ((decLenHistFlag_reg_118 = ap_const_lv1_0) and (heapCanzStream_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, heapCanzStream_empty_n, decLenHistFlag_reg_118)
    begin
                ap_block_pp0_stage0_subdone <= ((decLenHistFlag_reg_118 = ap_const_lv1_0) and (heapCanzStream_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(heapCanzStream_empty_n, decLenHistFlag_reg_118)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((decLenHistFlag_reg_118 = ap_const_lv1_0) and (heapCanzStream_empty_n = ap_const_logic_0));
    end process;


    ap_condition_357_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln927_fu_271_p2, grp_fu_234_p2, ap_phi_mux_decLenHistFlag_phi_fu_122_p4, ap_phi_mux_updSymBitsFlag_phi_fu_134_p4)
    begin
                ap_condition_357 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_phi_mux_updSymBitsFlag_phi_fu_134_p4 = ap_const_lv1_1) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_1)) or ((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_1) and (grp_fu_234_p2 = ap_const_lv1_1))) or ((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_0) and (grp_fu_234_p2 = ap_const_lv1_1))));
    end process;


    ap_condition_360_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln927_fu_271_p2, ap_block_pp0_stage0, grp_fu_234_p2)
    begin
                ap_condition_360 <= ((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (grp_fu_234_p2 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln927_fu_271_p2)
    begin
        if (((icmp_ln927_fu_271_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_count_V_7_phi_fu_171_p4_assign_proc : process(decLenHistFlag_reg_118, updSymBitsFlag_reg_130, icmp_ln927_reg_414, or_ln939_reg_418, or_ln931_reg_427, ap_phi_mux_count_i_3253_phi_fu_160_p6, count_V_11_fu_361_p2, ap_phi_reg_pp0_iter2_count_V_7_reg_168, tmp_322_fu_340_p3)
    begin
        if (((((updSymBitsFlag_reg_130 = ap_const_lv1_1) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (tmp_322_fu_340_p3 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1)) or ((decLenHistFlag_reg_118 = ap_const_lv1_1) and (tmp_322_fu_340_p3 = ap_const_lv1_1) and (or_ln931_reg_427 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) or ((decLenHistFlag_reg_118 = ap_const_lv1_0) and (tmp_322_fu_340_p3 = ap_const_lv1_1) and (or_ln939_reg_418 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1)))) then 
            ap_phi_mux_count_V_7_phi_fu_171_p4 <= ap_phi_mux_count_i_3253_phi_fu_160_p6;
        elsif (((((updSymBitsFlag_reg_130 = ap_const_lv1_1) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (tmp_322_fu_340_p3 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1)) or ((decLenHistFlag_reg_118 = ap_const_lv1_1) and (tmp_322_fu_340_p3 = ap_const_lv1_0) and (or_ln931_reg_427 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) or ((decLenHistFlag_reg_118 = ap_const_lv1_0) and (tmp_322_fu_340_p3 = ap_const_lv1_0) and (or_ln939_reg_418 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1)))) then 
            ap_phi_mux_count_V_7_phi_fu_171_p4 <= count_V_11_fu_361_p2;
        else 
            ap_phi_mux_count_V_7_phi_fu_171_p4 <= ap_phi_reg_pp0_iter2_count_V_7_reg_168;
        end if; 
    end process;


    ap_phi_mux_count_V_8_phi_fu_213_p6_assign_proc : process(decLenHistFlag_reg_118, updSymBitsFlag_reg_130, icmp_ln927_reg_414, or_ln939_reg_418, or_ln931_reg_427, count_V_5_fu_331_p1, ap_phi_mux_count_V_7_phi_fu_171_p4, ap_phi_reg_pp0_iter2_count_V_8_reg_210, count_V_10_fu_316_p1)
    begin
        if (((updSymBitsFlag_reg_130 = ap_const_lv1_0) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (or_ln931_reg_427 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
            ap_phi_mux_count_V_8_phi_fu_213_p6 <= count_V_5_fu_331_p1;
        elsif (((decLenHistFlag_reg_118 = ap_const_lv1_0) and (or_ln939_reg_418 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
            ap_phi_mux_count_V_8_phi_fu_213_p6 <= count_V_10_fu_316_p1;
        elsif (((((updSymBitsFlag_reg_130 = ap_const_lv1_1) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1)) or ((decLenHistFlag_reg_118 = ap_const_lv1_1) and (or_ln931_reg_427 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) or ((decLenHistFlag_reg_118 = ap_const_lv1_0) and (or_ln939_reg_418 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1)))) then 
            ap_phi_mux_count_V_8_phi_fu_213_p6 <= ap_phi_mux_count_V_7_phi_fu_171_p4;
        else 
            ap_phi_mux_count_V_8_phi_fu_213_p6 <= ap_phi_reg_pp0_iter2_count_V_8_reg_210;
        end if; 
    end process;


    ap_phi_mux_count_i_3253_phi_fu_160_p6_assign_proc : process(decLenHistFlag_reg_118, updSymBitsFlag_reg_130, icmp_ln927_reg_414, or_ln931_reg_427, ap_phi_reg_pp0_iter2_count_i_3253_reg_157, count_V_5_fu_331_p1)
    begin
        if (((updSymBitsFlag_reg_130 = ap_const_lv1_1) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (or_ln931_reg_427 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
            ap_phi_mux_count_i_3253_phi_fu_160_p6 <= count_V_5_fu_331_p1;
        else 
            ap_phi_mux_count_i_3253_phi_fu_160_p6 <= ap_phi_reg_pp0_iter2_count_i_3253_reg_157;
        end if; 
    end process;


    ap_phi_mux_decLenHistFlag_3_i256_phi_fu_198_p6_assign_proc : process(decLenHistFlag_reg_118, updSymBitsFlag_reg_130, icmp_ln927_reg_414, or_ln939_reg_418, or_ln931_reg_427, ap_phi_mux_decLenHistFlag_3_i257_phi_fu_146_p6, ap_phi_reg_pp0_iter2_decLenHistFlag_3_i256_reg_194)
    begin
        if ((((decLenHistFlag_reg_118 = ap_const_lv1_0) and (or_ln939_reg_418 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1)) or ((updSymBitsFlag_reg_130 = ap_const_lv1_0) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (or_ln931_reg_427 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1)))) then 
            ap_phi_mux_decLenHistFlag_3_i256_phi_fu_198_p6 <= ap_const_lv1_1;
        elsif (((((updSymBitsFlag_reg_130 = ap_const_lv1_1) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1)) or ((decLenHistFlag_reg_118 = ap_const_lv1_1) and (or_ln931_reg_427 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) or ((decLenHistFlag_reg_118 = ap_const_lv1_0) and (or_ln939_reg_418 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1)))) then 
            ap_phi_mux_decLenHistFlag_3_i256_phi_fu_198_p6 <= ap_phi_mux_decLenHistFlag_3_i257_phi_fu_146_p6;
        else 
            ap_phi_mux_decLenHistFlag_3_i256_phi_fu_198_p6 <= ap_phi_reg_pp0_iter2_decLenHistFlag_3_i256_reg_194;
        end if; 
    end process;


    ap_phi_mux_decLenHistFlag_3_i257_phi_fu_146_p6_assign_proc : process(decLenHistFlag_reg_118, updSymBitsFlag_reg_130, icmp_ln927_reg_414, or_ln931_reg_427, ap_phi_reg_pp0_iter2_decLenHistFlag_3_i257_reg_142)
    begin
        if (((updSymBitsFlag_reg_130 = ap_const_lv1_1) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (or_ln931_reg_427 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
            ap_phi_mux_decLenHistFlag_3_i257_phi_fu_146_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_decLenHistFlag_3_i257_phi_fu_146_p6 <= ap_phi_reg_pp0_iter2_decLenHistFlag_3_i257_reg_142;
        end if; 
    end process;


    ap_phi_mux_decLenHistFlag_phi_fu_122_p4_assign_proc : process(ap_enable_reg_pp0_iter2, decLenHistFlag_reg_118, ap_block_pp0_stage0, icmp_ln927_reg_414, ap_phi_mux_decLenHistFlag_3_i256_phi_fu_198_p6)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
            ap_phi_mux_decLenHistFlag_phi_fu_122_p4 <= ap_phi_mux_decLenHistFlag_3_i256_phi_fu_198_p6;
        else 
            ap_phi_mux_decLenHistFlag_phi_fu_122_p4 <= decLenHistFlag_reg_118;
        end if; 
    end process;


    ap_phi_mux_updSymBitsFlag_3_i258_phi_fu_182_p6_assign_proc : process(decLenHistFlag_reg_118, updSymBitsFlag_reg_130, icmp_ln927_reg_414, or_ln939_reg_418, or_ln931_reg_427, ap_phi_reg_pp0_iter2_updSymBitsFlag_3_i258_reg_178)
    begin
        if ((((decLenHistFlag_reg_118 = ap_const_lv1_0) and (or_ln939_reg_418 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1)) or ((updSymBitsFlag_reg_130 = ap_const_lv1_0) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (or_ln931_reg_427 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1)))) then 
            ap_phi_mux_updSymBitsFlag_3_i258_phi_fu_182_p6 <= ap_const_lv1_0;
        elsif (((((updSymBitsFlag_reg_130 = ap_const_lv1_1) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1)) or ((decLenHistFlag_reg_118 = ap_const_lv1_1) and (or_ln931_reg_427 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) or ((decLenHistFlag_reg_118 = ap_const_lv1_0) and (or_ln939_reg_418 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1)))) then 
            ap_phi_mux_updSymBitsFlag_3_i258_phi_fu_182_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_updSymBitsFlag_3_i258_phi_fu_182_p6 <= ap_phi_reg_pp0_iter2_updSymBitsFlag_3_i258_reg_178;
        end if; 
    end process;


    ap_phi_mux_updSymBitsFlag_phi_fu_134_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, updSymBitsFlag_reg_130, icmp_ln927_reg_414, ap_phi_mux_updSymBitsFlag_3_i258_phi_fu_182_p6)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
            ap_phi_mux_updSymBitsFlag_phi_fu_134_p4 <= ap_phi_mux_updSymBitsFlag_3_i258_phi_fu_182_p6;
        else 
            ap_phi_mux_updSymBitsFlag_phi_fu_134_p4 <= updSymBitsFlag_reg_130;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_count_i_3253_reg_157 <= "XXXXXXXXXX";
    ap_phi_reg_pp0_iter0_decLenHistFlag_3_i257_reg_142 <= "X";
    ap_phi_reg_pp0_iter2_count_V_7_reg_168 <= "XXXXXXXXXX";
    ap_phi_reg_pp0_iter2_count_V_8_reg_210 <= "XXXXXXXXXX";
    ap_phi_reg_pp0_iter2_decLenHistFlag_3_i256_reg_194 <= "X";
    ap_phi_reg_pp0_iter2_updSymBitsFlag_3_i258_reg_178 <= "X";

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_count_V_4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln927_reg_414, ap_phi_mux_count_V_8_phi_fu_213_p6, count_V_fu_68)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
            ap_sig_allocacmp_count_V_4 <= ap_phi_mux_count_V_8_phi_fu_213_p6;
        else 
            ap_sig_allocacmp_count_V_4 <= count_V_fu_68;
        end if; 
    end process;


    ap_sig_allocacmp_p_0_0_0_0_0_0230_load_assign_proc : process(ap_enable_reg_pp0_iter2, decLenHistFlag_reg_118, ap_block_pp0_stage0, icmp_ln927_reg_414, or_ln939_reg_418, p_0_0_0_0_0_0230_fu_56, trunc_ln145_fu_312_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (decLenHistFlag_reg_118 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (or_ln939_reg_418 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) then 
            ap_sig_allocacmp_p_0_0_0_0_0_0230_load <= trunc_ln145_fu_312_p1;
        else 
            ap_sig_allocacmp_p_0_0_0_0_0_0230_load <= p_0_0_0_0_0_0230_fu_56;
        end if; 
    end process;

    count_V_10_fu_316_p1 <= length_histogram_V_q0(10 - 1 downto 0);
    count_V_11_fu_361_p2 <= std_logic_vector(unsigned(ap_phi_mux_count_i_3253_phi_fu_160_p6) + unsigned(ap_const_lv10_3FF));
    count_V_5_fu_331_p1 <= length_histogram_V_q0(10 - 1 downto 0);
    grp_fu_222_p2 <= "0" when (ap_sig_allocacmp_count_V_4 = ap_const_lv10_0) else "1";
    grp_fu_227_p3 <= length_fu_64(15 downto 15);
    grp_fu_234_p2 <= (grp_fu_227_p3 or grp_fu_222_p2);
    grp_fu_240_p2 <= std_logic_vector(unsigned(length_fu_64) + unsigned(ap_const_lv16_FFFF));

    heapCanzStream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, heapCanzStream_empty_n, decLenHistFlag_reg_118, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (decLenHistFlag_reg_118 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            heapCanzStream_blk_n <= heapCanzStream_empty_n;
        else 
            heapCanzStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    heapCanzStream_read_assign_proc : process(ap_enable_reg_pp0_iter2, decLenHistFlag_reg_118, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (decLenHistFlag_reg_118 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            heapCanzStream_read <= ap_const_logic_1;
        else 
            heapCanzStream_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln927_fu_271_p2 <= "1" when (unsigned(k_fu_60) < unsigned(zext_ln1385_cast_reg_403)) else "0";
    k_5_fu_301_p2 <= std_logic_vector(unsigned(k_fu_60) + unsigned(ap_const_lv32_1));

    length_histogram_V_address0_assign_proc : process(ap_phi_mux_decLenHistFlag_phi_fu_122_p4, zext_ln941_fu_281_p1, zext_ln932_fu_291_p1, ap_condition_360)
    begin
        if ((ap_const_boolean_1 = ap_condition_360)) then
            if ((ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_1)) then 
                length_histogram_V_address0 <= zext_ln932_fu_291_p1(5 - 1 downto 0);
            elsif ((ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_0)) then 
                length_histogram_V_address0 <= zext_ln941_fu_281_p1(5 - 1 downto 0);
            else 
                length_histogram_V_address0 <= "XXXXX";
            end if;
        else 
            length_histogram_V_address0 <= "XXXXX";
        end if; 
    end process;


    length_histogram_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln927_fu_271_p2, ap_block_pp0_stage0_11001, grp_fu_234_p2, ap_phi_mux_decLenHistFlag_phi_fu_122_p4)
    begin
        if ((((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_1) and (grp_fu_234_p2 = ap_const_lv1_0)) or ((icmp_ln927_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_decLenHistFlag_phi_fu_122_p4 = ap_const_lv1_0) and (grp_fu_234_p2 = ap_const_lv1_0)))) then 
            length_histogram_V_ce0 <= ap_const_logic_1;
        else 
            length_histogram_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    symbol_bits_V_address0 <= zext_ln587_fu_356_p1(9 - 1 downto 0);

    symbol_bits_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            symbol_bits_V_ce0 <= ap_const_logic_1;
        else 
            symbol_bits_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    symbol_bits_V_d0 <= length_fu_64(4 - 1 downto 0);

    symbol_bits_V_we0_assign_proc : process(ap_enable_reg_pp0_iter2, decLenHistFlag_reg_118, updSymBitsFlag_reg_130, ap_block_pp0_stage0_11001, icmp_ln927_reg_414, or_ln939_reg_418, or_ln931_reg_427, tmp_322_fu_340_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((((updSymBitsFlag_reg_130 = ap_const_lv1_1) and (decLenHistFlag_reg_118 = ap_const_lv1_1) and (tmp_322_fu_340_p3 = ap_const_lv1_0) and (icmp_ln927_reg_414 = ap_const_lv1_1)) or ((decLenHistFlag_reg_118 = ap_const_lv1_1) and (tmp_322_fu_340_p3 = ap_const_lv1_0) and (or_ln931_reg_427 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))) or ((decLenHistFlag_reg_118 = ap_const_lv1_0) and (tmp_322_fu_340_p3 = ap_const_lv1_0) and (or_ln939_reg_418 = ap_const_lv1_1) and (icmp_ln927_reg_414 = ap_const_lv1_1))))) then 
            symbol_bits_V_we0 <= ap_const_logic_1;
        else 
            symbol_bits_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_322_fu_340_p3 <= length_fu_64(15 downto 15);
    trunc_ln145_fu_312_p1 <= heapCanzStream_dout(10 - 1 downto 0);
    zext_ln1385_cast_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1385),32));
    zext_ln587_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_p_0_0_0_0_0_0230_load),64));
    zext_ln932_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_240_p2),64));
    zext_ln941_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_240_p2),64));
end behav;
