// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gzipcMulticoreStreaming_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        coreStream_dout,
        coreStream_num_data_valid,
        coreStream_fifo_cap,
        coreStream_empty_n,
        coreStream_read,
        fileSizeStream_din,
        fileSizeStream_num_data_valid,
        fileSizeStream_fifo_cap,
        fileSizeStream_full_n,
        fileSizeStream_write,
        strdStream_din,
        strdStream_num_data_valid,
        strdStream_fifo_cap,
        strdStream_full_n,
        strdStream_write,
        strdSizeStream_din,
        strdSizeStream_num_data_valid,
        strdSizeStream_fifo_cap,
        strdSizeStream_full_n,
        strdSizeStream_write,
        blckEosStream_din,
        blckEosStream_num_data_valid,
        blckEosStream_fifo_cap,
        blckEosStream_full_n,
        blckEosStream_write,
        coreIdxStream_din,
        coreIdxStream_num_data_valid,
        coreIdxStream_fifo_cap,
        coreIdxStream_full_n,
        coreIdxStream_write,
        distStream_0_din,
        distStream_0_num_data_valid,
        distStream_0_fifo_cap,
        distStream_0_full_n,
        distStream_0_write,
        distStream_1_din,
        distStream_1_num_data_valid,
        distStream_1_fifo_cap,
        distStream_1_full_n,
        distStream_1_write,
        distStream_2_din,
        distStream_2_num_data_valid,
        distStream_2_fifo_cap,
        distStream_2_full_n,
        distStream_2_write,
        distStream_3_din,
        distStream_3_num_data_valid,
        distStream_3_fifo_cap,
        distStream_3_full_n,
        distStream_3_write,
        distStream_4_din,
        distStream_4_num_data_valid,
        distStream_4_fifo_cap,
        distStream_4_full_n,
        distStream_4_write,
        distStream_5_din,
        distStream_5_num_data_valid,
        distStream_5_fifo_cap,
        distStream_5_full_n,
        distStream_5_write,
        distStream_6_din,
        distStream_6_num_data_valid,
        distStream_6_fifo_cap,
        distStream_6_full_n,
        distStream_6_write,
        distStream_7_din,
        distStream_7_num_data_valid,
        distStream_7_fifo_cap,
        distStream_7_full_n,
        distStream_7_write
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [67:0] coreStream_dout;
input  [2:0] coreStream_num_data_valid;
input  [2:0] coreStream_fifo_cap;
input   coreStream_empty_n;
output   coreStream_read;
output  [31:0] fileSizeStream_din;
input  [5:0] fileSizeStream_num_data_valid;
input  [5:0] fileSizeStream_fifo_cap;
input   fileSizeStream_full_n;
output   fileSizeStream_write;
output  [63:0] strdStream_din;
input  [3:0] strdStream_num_data_valid;
input  [3:0] strdStream_fifo_cap;
input   strdStream_full_n;
output   strdStream_write;
output  [15:0] strdSizeStream_din;
input  [5:0] strdSizeStream_num_data_valid;
input  [5:0] strdSizeStream_fifo_cap;
input   strdSizeStream_full_n;
output   strdSizeStream_write;
output  [0:0] blckEosStream_din;
input  [7:0] blckEosStream_num_data_valid;
input  [7:0] blckEosStream_fifo_cap;
input   blckEosStream_full_n;
output   blckEosStream_write;
output  [3:0] coreIdxStream_din;
input  [5:0] coreIdxStream_num_data_valid;
input  [5:0] coreIdxStream_fifo_cap;
input   coreIdxStream_full_n;
output   coreIdxStream_write;
output  [67:0] distStream_0_din;
input  [9:0] distStream_0_num_data_valid;
input  [9:0] distStream_0_fifo_cap;
input   distStream_0_full_n;
output   distStream_0_write;
output  [67:0] distStream_1_din;
input  [9:0] distStream_1_num_data_valid;
input  [9:0] distStream_1_fifo_cap;
input   distStream_1_full_n;
output   distStream_1_write;
output  [67:0] distStream_2_din;
input  [9:0] distStream_2_num_data_valid;
input  [9:0] distStream_2_fifo_cap;
input   distStream_2_full_n;
output   distStream_2_write;
output  [67:0] distStream_3_din;
input  [9:0] distStream_3_num_data_valid;
input  [9:0] distStream_3_fifo_cap;
input   distStream_3_full_n;
output   distStream_3_write;
output  [67:0] distStream_4_din;
input  [9:0] distStream_4_num_data_valid;
input  [9:0] distStream_4_fifo_cap;
input   distStream_4_full_n;
output   distStream_4_write;
output  [67:0] distStream_5_din;
input  [9:0] distStream_5_num_data_valid;
input  [9:0] distStream_5_fifo_cap;
input   distStream_5_full_n;
output   distStream_5_write;
output  [67:0] distStream_6_din;
input  [9:0] distStream_6_num_data_valid;
input  [9:0] distStream_6_fifo_cap;
input   distStream_6_full_n;
output   distStream_6_write;
output  [67:0] distStream_7_din;
input  [9:0] distStream_7_num_data_valid;
input  [9:0] distStream_7_fifo_cap;
input   distStream_7_full_n;
output   distStream_7_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg coreStream_read;
reg strdStream_write;
reg strdSizeStream_write;
reg[67:0] distStream_0_din;
reg distStream_0_write;
reg[67:0] distStream_1_din;
reg distStream_1_write;
reg[67:0] distStream_2_din;
reg distStream_2_write;
reg[67:0] distStream_3_din;
reg distStream_3_write;
reg[67:0] distStream_4_din;
reg distStream_4_write;
reg[67:0] distStream_5_din;
reg distStream_5_write;
reg[67:0] distStream_6_din;
reg distStream_6_write;
reg[67:0] distStream_7_din;
reg distStream_7_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [3:0] core;
reg    fileSizeStream_blk_n;
wire    ap_CS_fsm_state16;
reg    blckEosStream_blk_n;
wire    ap_CS_fsm_state5;
reg    coreIdxStream_blk_n;
reg    distStream_0_blk_n;
wire    ap_CS_fsm_state8;
wire   [0:0] last_2_loc_load_load_fu_545_p1;
reg   [2:0] trunc_ln214_reg_741;
wire    ap_CS_fsm_state14;
reg   [0:0] endBlck_loc_load_reg_789;
reg   [0:0] icmp_ln253_reg_796;
reg   [3:0] reg_468;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln253_fu_600_p2;
reg   [0:0] icmp_ln258_reg_800;
reg    distStream_1_blk_n;
reg    distStream_2_blk_n;
reg    distStream_3_blk_n;
reg    distStream_4_blk_n;
reg    distStream_5_blk_n;
reg    distStream_6_blk_n;
reg    distStream_7_blk_n;
reg   [31:0] reg_449;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state11;
reg    ap_predicate_op166_write_state14;
reg    ap_predicate_op168_write_state14;
reg    ap_predicate_op170_write_state14;
reg    ap_predicate_op172_write_state14;
reg    ap_predicate_op174_write_state14;
reg    ap_predicate_op176_write_state14;
reg    ap_predicate_op178_write_state14;
reg    ap_predicate_op180_write_state14;
reg    ap_predicate_op187_write_state14;
reg    ap_predicate_op189_write_state14;
reg    ap_predicate_op191_write_state14;
reg    ap_predicate_op193_write_state14;
reg    ap_predicate_op195_write_state14;
reg    ap_predicate_op197_write_state14;
reg    ap_predicate_op199_write_state14;
reg    ap_predicate_op201_write_state14;
reg    ap_block_state14;
reg   [31:0] reg_456;
reg   [15:0] reg_462;
reg    ap_predicate_op142_write_state13;
reg    ap_predicate_op144_write_state13;
reg    ap_predicate_op146_write_state13;
reg    ap_predicate_op148_write_state13;
reg    ap_predicate_op150_write_state13;
reg    ap_predicate_op152_write_state13;
reg    ap_predicate_op154_write_state13;
reg    ap_predicate_op156_write_state13;
wire   [67:0] storedBufferStream_dout;
wire    storedBufferStream_empty_n;
reg    storedBufferStream_read;
reg    ap_predicate_op158_read_state13;
wire   [0:0] icmp_ln258_fu_606_p2;
reg    ap_predicate_op163_read_state13;
reg    ap_block_state13;
reg   [67:0] reg_473;
wire   [2:0] trunc_ln214_fu_515_p1;
wire   [0:0] empty_137_fu_520_p2;
reg   [0:0] empty_137_reg_747;
wire   [3:0] zext_ln214_fu_527_p1;
reg   [3:0] zext_ln214_reg_752;
reg    ap_predicate_op97_write_state8;
reg    ap_predicate_op99_write_state8;
reg    ap_predicate_op101_write_state8;
reg    ap_predicate_op103_write_state8;
reg    ap_predicate_op105_write_state8;
reg    ap_predicate_op107_write_state8;
reg    ap_predicate_op109_write_state8;
reg    ap_predicate_op111_write_state8;
reg    ap_block_state8;
reg   [0:0] last_2_loc_load_reg_767;
wire   [3:0] add_ln233_fu_548_p2;
wire    ap_CS_fsm_state9;
wire   [15:0] trunc_ln195_fu_577_p1;
reg   [15:0] trunc_ln195_reg_776;
wire   [0:0] empty_141_fu_581_p2;
reg   [0:0] empty_141_reg_781;
wire   [0:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_return;
reg   [0:0] targetBlock_reg_804;
wire    ap_CS_fsm_state15;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_done;
wire    grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_start;
wire    grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_done;
wire    grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_idle;
wire    grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_ready;
wire    grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_coreStream_read;
wire   [67:0] grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_storedBufferStream_din;
wire    grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_storedBufferStream_write;
wire   [7:0] grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_readSize_out;
wire    grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_readSize_out_ap_vld;
wire   [0:0] grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_last_out;
wire    grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_last_out_ap_vld;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_start;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_done;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_idle;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_ready;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_coreStream_read;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_storedBufferStream_read;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_6_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_6_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_5_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_5_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_4_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_4_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_3_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_3_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_2_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_2_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_1_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_1_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_0_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_0_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_7_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_7_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_storedBufferStream_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_storedBufferStream_write;
wire   [15:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_strdCntr_1_out;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_strdCntr_1_out_ap_vld;
wire   [31:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_writeSize_1_out;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_writeSize_1_out_ap_vld;
wire   [31:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_readSize_2_out;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_readSize_2_out_ap_vld;
wire   [0:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out_ap_vld;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_start;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_done;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_idle;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_ready;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_storedBufferStream_read;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_6_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_6_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_5_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_5_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_4_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_4_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_3_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_3_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_2_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_2_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_1_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_1_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_0_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_0_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_7_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_7_write;
wire   [15:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_strdCntr_3_out;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_strdCntr_3_out_ap_vld;
wire   [31:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_writeSize_2_out;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_writeSize_2_out_ap_vld;
wire   [0:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out_ap_vld;
wire   [0:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_icmp_ln240_1_out;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_icmp_ln240_1_out_ap_vld;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_start;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_idle;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_ready;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_storedBufferStream_read;
wire   [63:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdStream_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdStream_write;
wire   [15:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdSizeStream_din;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdSizeStream_write;
wire   [31:0] grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_writeSize_3_out;
wire    grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_writeSize_3_out_ap_vld;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_start;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_done;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_idle;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_ready;
wire   [67:0] grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_6_din;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_6_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_5_din;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_5_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_4_din;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_4_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_3_din;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_3_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_2_din;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_2_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_1_din;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_1_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_0_din;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_0_write;
wire   [67:0] grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_7_din;
wire    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_7_write;
reg   [0:0] last_1_reg_284;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state4;
reg   [3:0] empty_140_reg_293;
reg   [15:0] strdCntr_2_reg_302;
reg    grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [67:0] storedBufferStream_din;
wire    storedBufferStream_full_n;
reg    storedBufferStream_write;
reg    grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_start_reg;
wire    ap_CS_fsm_state12;
reg   [0:0] icmp_ln240_1_loc_fu_148;
reg    grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_start_reg;
reg    ap_block_state14_ignore_call2;
reg   [31:0] writeSize_3_loc_fu_144;
reg    grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_start_reg;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire   [3:0] grp_fu_443_p2;
reg   [31:0] readSize_1_fu_128;
wire   [31:0] zext_ln203_fu_506_p1;
reg   [31:0] writeSize_fu_132;
reg    ap_block_state1;
reg   [15:0] strdCntr_fu_136;
reg   [3:0] empty_fu_140;
reg    coreIdxStream_write_local;
reg   [0:0] blckEosStream_din_local;
reg    ap_block_state5;
reg    blckEosStream_write_local;
reg   [67:0] distStream_6_din_local;
reg    distStream_6_write_local;
reg   [67:0] distStream_5_din_local;
reg    distStream_5_write_local;
reg   [67:0] distStream_4_din_local;
reg    distStream_4_write_local;
reg   [67:0] distStream_3_din_local;
reg    distStream_3_write_local;
reg   [67:0] distStream_2_din_local;
reg    distStream_2_write_local;
reg   [67:0] distStream_1_din_local;
reg    distStream_1_write_local;
reg   [67:0] distStream_0_din_local;
reg    distStream_0_write_local;
reg   [67:0] distStream_7_din_local;
reg    distStream_7_write_local;
reg    storedBufferStream_read_local;
wire   [31:0] select_ln268_fu_627_p3;
reg    fileSizeStream_write_local;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 18'd1;
#0 core = 4'd0;
#0 grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_start_reg = 1'b0;
#0 grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_start_reg = 1'b0;
#0 grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_start_reg = 1'b0;
#0 grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_start_reg = 1'b0;
#0 grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_start_reg = 1'b0;
#0 readSize_1_fu_128 = 32'd0;
#0 writeSize_fu_132 = 32'd0;
#0 strdCntr_fu_136 = 16'd0;
#0 empty_fu_140 = 4'd0;
end

gzipcMulticoreStreaming_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_start),
    .ap_done(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_done),
    .ap_idle(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_idle),
    .ap_ready(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_ready),
    .coreStream_dout(coreStream_dout),
    .coreStream_num_data_valid(3'd0),
    .coreStream_fifo_cap(3'd0),
    .coreStream_empty_n(coreStream_empty_n),
    .coreStream_read(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_coreStream_read),
    .storedBufferStream_din(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_storedBufferStream_din),
    .storedBufferStream_full_n(storedBufferStream_full_n),
    .storedBufferStream_write(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_storedBufferStream_write),
    .readSize_out(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_readSize_out),
    .readSize_out_ap_vld(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_readSize_out_ap_vld),
    .last_out(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_last_out),
    .last_out_ap_vld(grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_last_out_ap_vld)
);

gzipcMulticoreStreaming_multicoreDistributor_Pipeline_VITIS_LOOP_217_1 grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_start),
    .ap_done(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_done),
    .ap_idle(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_idle),
    .ap_ready(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_ready),
    .coreStream_dout(coreStream_dout),
    .coreStream_num_data_valid(3'd0),
    .coreStream_fifo_cap(3'd0),
    .coreStream_empty_n(coreStream_empty_n),
    .coreStream_read(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_coreStream_read),
    .storedBufferStream_dout(storedBufferStream_dout),
    .storedBufferStream_empty_n(storedBufferStream_empty_n),
    .storedBufferStream_read(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_storedBufferStream_read),
    .distStream_6_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_6_din),
    .distStream_6_num_data_valid(10'd0),
    .distStream_6_fifo_cap(10'd0),
    .distStream_6_full_n(distStream_6_full_n),
    .distStream_6_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_6_write),
    .distStream_5_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_5_din),
    .distStream_5_num_data_valid(10'd0),
    .distStream_5_fifo_cap(10'd0),
    .distStream_5_full_n(distStream_5_full_n),
    .distStream_5_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_5_write),
    .distStream_4_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_4_din),
    .distStream_4_num_data_valid(10'd0),
    .distStream_4_fifo_cap(10'd0),
    .distStream_4_full_n(distStream_4_full_n),
    .distStream_4_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_4_write),
    .distStream_3_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_3_din),
    .distStream_3_num_data_valid(10'd0),
    .distStream_3_fifo_cap(10'd0),
    .distStream_3_full_n(distStream_3_full_n),
    .distStream_3_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_3_write),
    .distStream_2_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_2_din),
    .distStream_2_num_data_valid(10'd0),
    .distStream_2_fifo_cap(10'd0),
    .distStream_2_full_n(distStream_2_full_n),
    .distStream_2_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_2_write),
    .distStream_1_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_1_din),
    .distStream_1_num_data_valid(10'd0),
    .distStream_1_fifo_cap(10'd0),
    .distStream_1_full_n(distStream_1_full_n),
    .distStream_1_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_1_write),
    .distStream_0_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_0_din),
    .distStream_0_num_data_valid(10'd0),
    .distStream_0_fifo_cap(10'd0),
    .distStream_0_full_n(distStream_0_full_n),
    .distStream_0_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_0_write),
    .distStream_7_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_7_din),
    .distStream_7_num_data_valid(10'd0),
    .distStream_7_fifo_cap(10'd0),
    .distStream_7_full_n(distStream_7_full_n),
    .distStream_7_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_7_write),
    .storedBufferStream_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_storedBufferStream_din),
    .storedBufferStream_full_n(storedBufferStream_full_n),
    .storedBufferStream_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_storedBufferStream_write),
    .strdCntr(reg_462),
    .writeSize(reg_456),
    .readSize_1(reg_449),
    .empty_51(trunc_ln214_reg_741),
    .empty(empty_137_reg_747),
    .strdCntr_1_out(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_strdCntr_1_out),
    .strdCntr_1_out_ap_vld(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_strdCntr_1_out_ap_vld),
    .writeSize_1_out(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_writeSize_1_out),
    .writeSize_1_out_ap_vld(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_writeSize_1_out_ap_vld),
    .readSize_2_out(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_readSize_2_out),
    .readSize_2_out_ap_vld(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_readSize_2_out_ap_vld),
    .last_2_out(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out),
    .last_2_out_ap_vld(grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out_ap_vld)
);

gzipcMulticoreStreaming_multicoreDistributor_Pipeline_VITIS_LOOP_240_2 grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_start),
    .ap_done(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_done),
    .ap_idle(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_idle),
    .ap_ready(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_ready),
    .storedBufferStream_dout(storedBufferStream_dout),
    .storedBufferStream_empty_n(storedBufferStream_empty_n),
    .storedBufferStream_read(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_storedBufferStream_read),
    .distStream_6_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_6_din),
    .distStream_6_num_data_valid(10'd0),
    .distStream_6_fifo_cap(10'd0),
    .distStream_6_full_n(distStream_6_full_n),
    .distStream_6_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_6_write),
    .distStream_5_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_5_din),
    .distStream_5_num_data_valid(10'd0),
    .distStream_5_fifo_cap(10'd0),
    .distStream_5_full_n(distStream_5_full_n),
    .distStream_5_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_5_write),
    .distStream_4_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_4_din),
    .distStream_4_num_data_valid(10'd0),
    .distStream_4_fifo_cap(10'd0),
    .distStream_4_full_n(distStream_4_full_n),
    .distStream_4_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_4_write),
    .distStream_3_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_3_din),
    .distStream_3_num_data_valid(10'd0),
    .distStream_3_fifo_cap(10'd0),
    .distStream_3_full_n(distStream_3_full_n),
    .distStream_3_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_3_write),
    .distStream_2_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_2_din),
    .distStream_2_num_data_valid(10'd0),
    .distStream_2_fifo_cap(10'd0),
    .distStream_2_full_n(distStream_2_full_n),
    .distStream_2_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_2_write),
    .distStream_1_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_1_din),
    .distStream_1_num_data_valid(10'd0),
    .distStream_1_fifo_cap(10'd0),
    .distStream_1_full_n(distStream_1_full_n),
    .distStream_1_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_1_write),
    .distStream_0_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_0_din),
    .distStream_0_num_data_valid(10'd0),
    .distStream_0_fifo_cap(10'd0),
    .distStream_0_full_n(distStream_0_full_n),
    .distStream_0_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_0_write),
    .distStream_7_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_7_din),
    .distStream_7_num_data_valid(10'd0),
    .distStream_7_fifo_cap(10'd0),
    .distStream_7_full_n(distStream_7_full_n),
    .distStream_7_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_7_write),
    .strdCntr(reg_462),
    .writeSize(reg_456),
    .readSize_1(reg_449),
    .empty_50(reg_468),
    .empty(empty_141_reg_781),
    .strdCntr_3_out(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_strdCntr_3_out),
    .strdCntr_3_out_ap_vld(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_strdCntr_3_out_ap_vld),
    .writeSize_2_out(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_writeSize_2_out),
    .writeSize_2_out_ap_vld(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_writeSize_2_out_ap_vld),
    .endBlck_out(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out),
    .endBlck_out_ap_vld(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out_ap_vld),
    .icmp_ln240_1_out(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_icmp_ln240_1_out),
    .icmp_ln240_1_out_ap_vld(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_icmp_ln240_1_out_ap_vld)
);

gzipcMulticoreStreaming_multicoreDistributor_Pipeline_VITIS_LOOP_263_3 grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_start),
    .ap_done(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_done),
    .ap_idle(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_idle),
    .ap_ready(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_ready),
    .writeSize_2_reload(grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_writeSize_2_out),
    .readSize_1(reg_449),
    .icmp_ln240_1_reload(icmp_ln240_1_loc_fu_148),
    .storedBufferStream_dout(storedBufferStream_dout),
    .storedBufferStream_empty_n(storedBufferStream_empty_n),
    .storedBufferStream_read(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_storedBufferStream_read),
    .strdStream_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdStream_din),
    .strdStream_num_data_valid(4'd0),
    .strdStream_fifo_cap(4'd0),
    .strdStream_full_n(strdStream_full_n),
    .strdStream_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdStream_write),
    .empty(trunc_ln195_reg_776),
    .strdSizeStream_din(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdSizeStream_din),
    .strdSizeStream_num_data_valid(6'd0),
    .strdSizeStream_fifo_cap(6'd0),
    .strdSizeStream_full_n(strdSizeStream_full_n),
    .strdSizeStream_write(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdSizeStream_write),
    .writeSize_3_out(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_writeSize_3_out),
    .writeSize_3_out_ap_vld(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_writeSize_3_out_ap_vld),
    .ap_return(grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_return)
);

gzipcMulticoreStreaming_multicoreDistributor_Pipeline_ip_terminate_data grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_start),
    .ap_done(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_done),
    .ap_idle(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_idle),
    .ap_ready(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_ready),
    .distStream_6_din(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_6_din),
    .distStream_6_num_data_valid(10'd0),
    .distStream_6_fifo_cap(10'd0),
    .distStream_6_full_n(distStream_6_full_n),
    .distStream_6_write(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_6_write),
    .distStream_5_din(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_5_din),
    .distStream_5_num_data_valid(10'd0),
    .distStream_5_fifo_cap(10'd0),
    .distStream_5_full_n(distStream_5_full_n),
    .distStream_5_write(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_5_write),
    .distStream_4_din(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_4_din),
    .distStream_4_num_data_valid(10'd0),
    .distStream_4_fifo_cap(10'd0),
    .distStream_4_full_n(distStream_4_full_n),
    .distStream_4_write(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_4_write),
    .distStream_3_din(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_3_din),
    .distStream_3_num_data_valid(10'd0),
    .distStream_3_fifo_cap(10'd0),
    .distStream_3_full_n(distStream_3_full_n),
    .distStream_3_write(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_3_write),
    .distStream_2_din(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_2_din),
    .distStream_2_num_data_valid(10'd0),
    .distStream_2_fifo_cap(10'd0),
    .distStream_2_full_n(distStream_2_full_n),
    .distStream_2_write(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_2_write),
    .distStream_1_din(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_1_din),
    .distStream_1_num_data_valid(10'd0),
    .distStream_1_fifo_cap(10'd0),
    .distStream_1_full_n(distStream_1_full_n),
    .distStream_1_write(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_1_write),
    .distStream_0_din(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_0_din),
    .distStream_0_num_data_valid(10'd0),
    .distStream_0_fifo_cap(10'd0),
    .distStream_0_full_n(distStream_0_full_n),
    .distStream_0_write(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_0_write),
    .distStream_7_din(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_7_din),
    .distStream_7_num_data_valid(10'd0),
    .distStream_7_fifo_cap(10'd0),
    .distStream_7_full_n(distStream_7_full_n),
    .distStream_7_write(grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_7_write)
);

gzipcMulticoreStreaming_fifo_w68_d18_A storedBufferStream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(storedBufferStream_din),
    .if_full_n(storedBufferStream_full_n),
    .if_write(storedBufferStream_write),
    .if_dout(storedBufferStream_dout),
    .if_empty_n(storedBufferStream_empty_n),
    .if_read(storedBufferStream_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_start_reg <= 1'b1;
        end else if ((grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_ready == 1'b1)) begin
            grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_start_reg <= 1'b1;
        end else if ((grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_ready == 1'b1)) begin
            grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state14_ignore_call2) & (1'b1 == ap_CS_fsm_state14))) begin
            grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_start_reg <= 1'b1;
        end else if ((grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_ready == 1'b1)) begin
            grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_start_reg <= 1'b1;
        end else if ((grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_ready == 1'b1)) begin
            grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_start_reg <= 1'b1;
        end else if ((grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_ready == 1'b1)) begin
            grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8))) begin
        core <= zext_ln214_fu_527_p1;
    end else if (((last_2_loc_load_reg_767 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        core <= add_ln233_fu_548_p2;
    end else if ((((1'b0 == ap_block_state14) & (icmp_ln258_reg_800 == 1'd0) & (1'b1 == ap_CS_fsm_state14) & (endBlck_loc_load_reg_789 == 1'd1)) | ((1'b0 == ap_block_state14) & (1'b1 == ap_CS_fsm_state14) & (endBlck_loc_load_reg_789 == 1'd0)))) begin
        core <= grp_fu_443_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8) & (last_2_loc_load_load_fu_545_p1 == 1'd1))) begin
        empty_140_reg_293 <= zext_ln214_fu_527_p1;
    end else if (((last_2_loc_load_reg_767 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        empty_140_reg_293 <= add_ln233_fu_548_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_fu_140 <= core;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        empty_fu_140 <= empty_140_reg_293;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        last_1_reg_284 <= grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_last_out;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        last_1_reg_284 <= grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        readSize_1_fu_128 <= zext_ln203_fu_506_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        readSize_1_fu_128 <= grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_readSize_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8) & (last_2_loc_load_load_fu_545_p1 == 1'd1))) begin
        strdCntr_2_reg_302 <= grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_strdCntr_1_out;
    end else if (((last_2_loc_load_reg_767 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        strdCntr_2_reg_302 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        strdCntr_fu_136 <= 16'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        strdCntr_fu_136 <= strdCntr_2_reg_302;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        writeSize_fu_132 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        writeSize_fu_132 <= grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_writeSize_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        empty_137_reg_747 <= empty_137_fu_520_p2;
        trunc_ln214_reg_741 <= trunc_ln214_fu_515_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        empty_141_reg_781 <= empty_141_fu_581_p2;
        trunc_ln195_reg_776 <= trunc_ln195_fu_577_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13))) begin
        endBlck_loc_load_reg_789 <= grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out;
        icmp_ln253_reg_796 <= icmp_ln253_fu_600_p2;
        icmp_ln258_reg_800 <= icmp_ln258_fu_606_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_icmp_ln240_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        icmp_ln240_1_loc_fu_148 <= grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_icmp_ln240_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8))) begin
        last_2_loc_load_reg_767 <= grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out;
        zext_ln214_reg_752[2 : 0] <= zext_ln214_fu_527_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6) | ((1'b0 == ap_block_state14) & (1'b1 == ap_CS_fsm_state14)))) begin
        reg_449 <= readSize_1_fu_128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6))) begin
        reg_456 <= writeSize_fu_132;
        reg_462 <= strdCntr_fu_136;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0)) | ((icmp_ln258_fu_606_p2 == 1'd0) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd1)))) begin
        reg_468 <= empty_fu_140;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_op163_read_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)) | ((ap_predicate_op158_read_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)))) begin
        reg_473 <= storedBufferStream_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        targetBlock_reg_804 <= grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_writeSize_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        writeSize_3_loc_fu_144 <= grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_writeSize_3_out;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state13)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state14)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((fileSizeStream_full_n == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state8)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state5) & (last_1_reg_284 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (last_1_reg_284 == 1'd0)))) begin
        blckEosStream_blk_n = blckEosStream_full_n;
    end else begin
        blckEosStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
        if ((last_1_reg_284 == 1'd1)) begin
            blckEosStream_din_local = 1'd1;
        end else if ((last_1_reg_284 == 1'd0)) begin
            blckEosStream_din_local = 1'd0;
        end else begin
            blckEosStream_din_local = 'bx;
        end
    end else begin
        blckEosStream_din_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5) & (last_1_reg_284 == 1'd1)) | ((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5) & (last_1_reg_284 == 1'd0)))) begin
        blckEosStream_write_local = 1'b1;
    end else begin
        blckEosStream_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        coreIdxStream_blk_n = coreIdxStream_full_n;
    end else begin
        coreIdxStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        coreIdxStream_write_local = 1'b1;
    end else begin
        coreIdxStream_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        coreStream_read = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_coreStream_read;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        coreStream_read = grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_coreStream_read;
    end else begin
        coreStream_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln258_reg_800 == 1'd0) & (1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd0) & (endBlck_loc_load_reg_789 == 1'd1)) | ((empty_fu_140 == 4'd0) & (icmp_ln253_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0)) | ((1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd0) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0)) | ((1'b1 == ap_CS_fsm_state8) & (trunc_ln214_reg_741 == 3'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0)))) begin
        distStream_0_blk_n = distStream_0_full_n;
    end else begin
        distStream_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_0_din = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_0_din;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_0_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_0_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_0_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_0_din;
    end else begin
        distStream_0_din = distStream_0_din_local;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state14) & (ap_predicate_op199_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op178_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_0_din_local = reg_473;
    end else if ((((ap_predicate_op109_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op154_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)))) begin
        distStream_0_din_local = 68'd0;
    end else begin
        distStream_0_din_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_0_write = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_0_write;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_0_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_0_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_0_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_0_write;
    end else begin
        distStream_0_write = distStream_0_write_local;
    end
end

always @ (*) begin
    if ((((ap_predicate_op109_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op154_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state14) & (ap_predicate_op199_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op178_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_0_write_local = 1'b1;
    end else begin
        distStream_0_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((((empty_fu_140 == 4'd1) & (icmp_ln253_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0)) | ((icmp_ln258_reg_800 == 1'd0) & (1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd1) & (endBlck_loc_load_reg_789 == 1'd1)) | ((1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd1) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0)) | ((1'b1 == ap_CS_fsm_state8) & (trunc_ln214_reg_741 == 3'd1) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0)))) begin
        distStream_1_blk_n = distStream_1_full_n;
    end else begin
        distStream_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_1_din = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_1_din;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_1_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_1_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_1_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_1_din;
    end else begin
        distStream_1_din = distStream_1_din_local;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state14) & (ap_predicate_op197_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op176_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_1_din_local = reg_473;
    end else if ((((ap_predicate_op107_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op152_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)))) begin
        distStream_1_din_local = 68'd0;
    end else begin
        distStream_1_din_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_1_write = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_1_write;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_1_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_1_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_1_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_1_write;
    end else begin
        distStream_1_write = distStream_1_write_local;
    end
end

always @ (*) begin
    if ((((ap_predicate_op107_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op152_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state14) & (ap_predicate_op197_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op176_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_1_write_local = 1'b1;
    end else begin
        distStream_1_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((((empty_fu_140 == 4'd2) & (icmp_ln253_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0)) | ((icmp_ln258_reg_800 == 1'd0) & (1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd2) & (endBlck_loc_load_reg_789 == 1'd1)) | ((1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd2) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0)) | ((1'b1 == ap_CS_fsm_state8) & (trunc_ln214_reg_741 == 3'd2) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0)))) begin
        distStream_2_blk_n = distStream_2_full_n;
    end else begin
        distStream_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_2_din = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_2_din;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_2_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_2_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_2_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_2_din;
    end else begin
        distStream_2_din = distStream_2_din_local;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state14) & (ap_predicate_op195_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op174_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_2_din_local = reg_473;
    end else if ((((ap_predicate_op105_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op150_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)))) begin
        distStream_2_din_local = 68'd0;
    end else begin
        distStream_2_din_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_2_write = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_2_write;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_2_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_2_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_2_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_2_write;
    end else begin
        distStream_2_write = distStream_2_write_local;
    end
end

always @ (*) begin
    if ((((ap_predicate_op105_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op150_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state14) & (ap_predicate_op195_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op174_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_2_write_local = 1'b1;
    end else begin
        distStream_2_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((((empty_fu_140 == 4'd3) & (icmp_ln253_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0)) | ((icmp_ln258_reg_800 == 1'd0) & (1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd3) & (endBlck_loc_load_reg_789 == 1'd1)) | ((1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd3) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0)) | ((1'b1 == ap_CS_fsm_state8) & (trunc_ln214_reg_741 == 3'd3) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0)))) begin
        distStream_3_blk_n = distStream_3_full_n;
    end else begin
        distStream_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_3_din = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_3_din;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_3_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_3_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_3_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_3_din;
    end else begin
        distStream_3_din = distStream_3_din_local;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state14) & (ap_predicate_op193_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op172_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_3_din_local = reg_473;
    end else if ((((ap_predicate_op103_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op148_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)))) begin
        distStream_3_din_local = 68'd0;
    end else begin
        distStream_3_din_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_3_write = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_3_write;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_3_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_3_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_3_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_3_write;
    end else begin
        distStream_3_write = distStream_3_write_local;
    end
end

always @ (*) begin
    if ((((ap_predicate_op103_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op148_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state14) & (ap_predicate_op193_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op172_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_3_write_local = 1'b1;
    end else begin
        distStream_3_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((((empty_fu_140 == 4'd4) & (icmp_ln253_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0)) | ((icmp_ln258_reg_800 == 1'd0) & (1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd4) & (endBlck_loc_load_reg_789 == 1'd1)) | ((1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd4) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0)) | ((1'b1 == ap_CS_fsm_state8) & (trunc_ln214_reg_741 == 3'd4) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0)))) begin
        distStream_4_blk_n = distStream_4_full_n;
    end else begin
        distStream_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_4_din = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_4_din;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_4_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_4_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_4_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_4_din;
    end else begin
        distStream_4_din = distStream_4_din_local;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state14) & (ap_predicate_op191_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op170_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_4_din_local = reg_473;
    end else if ((((ap_predicate_op101_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op146_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)))) begin
        distStream_4_din_local = 68'd0;
    end else begin
        distStream_4_din_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_4_write = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_4_write;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_4_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_4_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_4_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_4_write;
    end else begin
        distStream_4_write = distStream_4_write_local;
    end
end

always @ (*) begin
    if ((((ap_predicate_op101_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op146_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state14) & (ap_predicate_op191_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op170_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_4_write_local = 1'b1;
    end else begin
        distStream_4_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((((empty_fu_140 == 4'd5) & (icmp_ln253_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0)) | ((icmp_ln258_reg_800 == 1'd0) & (1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd5) & (endBlck_loc_load_reg_789 == 1'd1)) | ((1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd5) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0)) | ((1'b1 == ap_CS_fsm_state8) & (trunc_ln214_reg_741 == 3'd5) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0)))) begin
        distStream_5_blk_n = distStream_5_full_n;
    end else begin
        distStream_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_5_din = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_5_din;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_5_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_5_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_5_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_5_din;
    end else begin
        distStream_5_din = distStream_5_din_local;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state14) & (ap_predicate_op189_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op168_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_5_din_local = reg_473;
    end else if ((((ap_predicate_op99_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op144_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)))) begin
        distStream_5_din_local = 68'd0;
    end else begin
        distStream_5_din_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_5_write = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_5_write;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_5_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_5_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_5_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_5_write;
    end else begin
        distStream_5_write = distStream_5_write_local;
    end
end

always @ (*) begin
    if ((((ap_predicate_op99_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op144_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state14) & (ap_predicate_op189_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op168_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_5_write_local = 1'b1;
    end else begin
        distStream_5_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((((empty_fu_140 == 4'd6) & (icmp_ln253_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0)) | ((icmp_ln258_reg_800 == 1'd0) & (1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd6) & (endBlck_loc_load_reg_789 == 1'd1)) | ((1'b1 == ap_CS_fsm_state14) & (reg_468 == 4'd6) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0)) | ((1'b1 == ap_CS_fsm_state8) & (trunc_ln214_reg_741 == 3'd6) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0)))) begin
        distStream_6_blk_n = distStream_6_full_n;
    end else begin
        distStream_6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_6_din = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_6_din;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_6_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_6_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_6_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_6_din;
    end else begin
        distStream_6_din = distStream_6_din_local;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state14) & (ap_predicate_op187_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op166_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_6_din_local = reg_473;
    end else if ((((ap_predicate_op97_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op142_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)))) begin
        distStream_6_din_local = 68'd0;
    end else begin
        distStream_6_din_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_6_write = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_6_write;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_6_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_6_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_6_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_6_write;
    end else begin
        distStream_6_write = distStream_6_write_local;
    end
end

always @ (*) begin
    if ((((ap_predicate_op97_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op142_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state14) & (ap_predicate_op187_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op166_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_6_write_local = 1'b1;
    end else begin
        distStream_6_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((~(empty_fu_140 == 4'd6) & ~(empty_fu_140 == 4'd5) & ~(empty_fu_140 == 4'd4) & ~(empty_fu_140 == 4'd3) & ~(empty_fu_140 == 4'd2) & ~(empty_fu_140 == 4'd1) & ~(empty_fu_140 == 4'd0) & (icmp_ln253_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0)) | (~(reg_468 == 4'd6) & ~(reg_468 == 4'd5) & ~(reg_468 == 4'd4) & ~(reg_468 == 4'd3) & ~(reg_468 == 4'd2) & ~(reg_468 == 4'd1) & ~(reg_468 == 4'd0) & (icmp_ln258_reg_800 == 1'd0) & (1'b1 == ap_CS_fsm_state14) & (endBlck_loc_load_reg_789 == 1'd1)) | (~(reg_468 == 4'd6) & ~(reg_468 == 4'd5) & ~(reg_468 == 4'd4) & ~(reg_468 == 4'd3) & ~(reg_468 == 4'd2) & ~(reg_468 == 4'd1) & ~(reg_468 == 4'd0) & (1'b1 == ap_CS_fsm_state14) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0)) | ((1'b1 == ap_CS_fsm_state8) & (trunc_ln214_reg_741 == 3'd7) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0)))) begin
        distStream_7_blk_n = distStream_7_full_n;
    end else begin
        distStream_7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_7_din = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_7_din;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_7_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_7_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_7_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_7_din;
    end else begin
        distStream_7_din = distStream_7_din_local;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state14) & (ap_predicate_op201_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op180_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_7_din_local = reg_473;
    end else if ((((ap_predicate_op111_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op156_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)))) begin
        distStream_7_din_local = 68'd0;
    end else begin
        distStream_7_din_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        distStream_7_write = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_distStream_7_write;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distStream_7_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_distStream_7_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        distStream_7_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_distStream_7_write;
    end else begin
        distStream_7_write = distStream_7_write_local;
    end
end

always @ (*) begin
    if ((((ap_predicate_op111_write_state8 == 1'b1) & (1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((ap_predicate_op156_write_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state14) & (ap_predicate_op201_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state14) & (ap_predicate_op180_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)))) begin
        distStream_7_write_local = 1'b1;
    end else begin
        distStream_7_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        fileSizeStream_blk_n = fileSizeStream_full_n;
    end else begin
        fileSizeStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((fileSizeStream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        fileSizeStream_write_local = 1'b1;
    end else begin
        fileSizeStream_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        storedBufferStream_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_storedBufferStream_din;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        storedBufferStream_din = grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_storedBufferStream_din;
    end else begin
        storedBufferStream_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_storedBufferStream_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        storedBufferStream_read = grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_storedBufferStream_read;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        storedBufferStream_read = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_storedBufferStream_read;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        storedBufferStream_read = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_storedBufferStream_read;
    end else begin
        storedBufferStream_read = storedBufferStream_read_local;
    end
end

always @ (*) begin
    if ((((ap_predicate_op163_read_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)) | ((ap_predicate_op158_read_state13 == 1'b1) & (1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13)))) begin
        storedBufferStream_read_local = 1'b1;
    end else begin
        storedBufferStream_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        storedBufferStream_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_storedBufferStream_write;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        storedBufferStream_write = grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_storedBufferStream_write;
    end else begin
        storedBufferStream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        strdSizeStream_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdSizeStream_write;
    end else begin
        strdSizeStream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        strdStream_write = grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdStream_write;
    end else begin
        strdStream_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5) & (last_1_reg_284 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5) & (last_1_reg_284 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((1'b0 == ap_block_state14) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((fileSizeStream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln233_fu_548_p2 = (zext_ln214_reg_752 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((coreIdxStream_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state13 = (((ap_predicate_op163_read_state13 == 1'b1) & (storedBufferStream_empty_n == 1'b0)) | ((ap_predicate_op158_read_state13 == 1'b1) & (storedBufferStream_empty_n == 1'b0)) | ((ap_predicate_op156_write_state13 == 1'b1) & (distStream_7_full_n == 1'b0)) | ((ap_predicate_op152_write_state13 == 1'b1) & (distStream_1_full_n == 1'b0)) | ((ap_predicate_op150_write_state13 == 1'b1) & (distStream_2_full_n == 1'b0)) | ((ap_predicate_op148_write_state13 == 1'b1) & (distStream_3_full_n == 1'b0)) | ((ap_predicate_op146_write_state13 == 1'b1) & (distStream_4_full_n == 1'b0)) | ((ap_predicate_op144_write_state13 == 1'b1) & (distStream_5_full_n == 1'b0)) | ((ap_predicate_op142_write_state13 == 1'b1) & (distStream_6_full_n == 1'b0)) | ((distStream_0_full_n == 1'b0) & (ap_predicate_op154_write_state13 == 1'b1)));
end

always @ (*) begin
    ap_block_state14 = (((ap_predicate_op201_write_state14 == 1'b1) & (distStream_7_full_n == 1'b0)) | ((ap_predicate_op197_write_state14 == 1'b1) & (distStream_1_full_n == 1'b0)) | ((ap_predicate_op195_write_state14 == 1'b1) & (distStream_2_full_n == 1'b0)) | ((ap_predicate_op193_write_state14 == 1'b1) & (distStream_3_full_n == 1'b0)) | ((ap_predicate_op191_write_state14 == 1'b1) & (distStream_4_full_n == 1'b0)) | ((ap_predicate_op189_write_state14 == 1'b1) & (distStream_5_full_n == 1'b0)) | ((ap_predicate_op187_write_state14 == 1'b1) & (distStream_6_full_n == 1'b0)) | ((ap_predicate_op180_write_state14 == 1'b1) & (distStream_7_full_n == 1'b0)) | ((distStream_0_full_n == 1'b0) & (ap_predicate_op199_write_state14 == 1'b1)) | ((distStream_0_full_n == 1'b0) & (ap_predicate_op178_write_state14 == 1'b1)) | ((ap_predicate_op176_write_state14 == 1'b1) & (distStream_1_full_n == 1'b0)) | ((ap_predicate_op174_write_state14 == 1'b1) & (distStream_2_full_n == 1'b0)) | ((ap_predicate_op172_write_state14 == 1'b1) & (distStream_3_full_n == 1'b0)) 
    | ((ap_predicate_op170_write_state14 == 1'b1) & (distStream_4_full_n == 1'b0)) | ((ap_predicate_op168_write_state14 == 1'b1) & (distStream_5_full_n == 1'b0)) | ((ap_predicate_op166_write_state14 == 1'b1) & (distStream_6_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state14_ignore_call2 = (((ap_predicate_op201_write_state14 == 1'b1) & (distStream_7_full_n == 1'b0)) | ((ap_predicate_op197_write_state14 == 1'b1) & (distStream_1_full_n == 1'b0)) | ((ap_predicate_op195_write_state14 == 1'b1) & (distStream_2_full_n == 1'b0)) | ((ap_predicate_op193_write_state14 == 1'b1) & (distStream_3_full_n == 1'b0)) | ((ap_predicate_op191_write_state14 == 1'b1) & (distStream_4_full_n == 1'b0)) | ((ap_predicate_op189_write_state14 == 1'b1) & (distStream_5_full_n == 1'b0)) | ((ap_predicate_op187_write_state14 == 1'b1) & (distStream_6_full_n == 1'b0)) | ((ap_predicate_op180_write_state14 == 1'b1) & (distStream_7_full_n == 1'b0)) | ((distStream_0_full_n == 1'b0) & (ap_predicate_op199_write_state14 == 1'b1)) | ((distStream_0_full_n == 1'b0) & (ap_predicate_op178_write_state14 == 1'b1)) | ((ap_predicate_op176_write_state14 == 1'b1) & (distStream_1_full_n == 1'b0)) | ((ap_predicate_op174_write_state14 == 1'b1) & (distStream_2_full_n == 1'b0)) | ((ap_predicate_op172_write_state14 == 1'b1) & (distStream_3_full_n == 1'b0)) 
    | ((ap_predicate_op170_write_state14 == 1'b1) & (distStream_4_full_n == 1'b0)) | ((ap_predicate_op168_write_state14 == 1'b1) & (distStream_5_full_n == 1'b0)) | ((ap_predicate_op166_write_state14 == 1'b1) & (distStream_6_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5 = (((blckEosStream_full_n == 1'b0) & (last_1_reg_284 == 1'd1)) | ((blckEosStream_full_n == 1'b0) & (last_1_reg_284 == 1'd0)));
end

always @ (*) begin
    ap_block_state8 = (((ap_predicate_op111_write_state8 == 1'b1) & (distStream_7_full_n == 1'b0)) | ((ap_predicate_op107_write_state8 == 1'b1) & (distStream_1_full_n == 1'b0)) | ((ap_predicate_op105_write_state8 == 1'b1) & (distStream_2_full_n == 1'b0)) | ((ap_predicate_op103_write_state8 == 1'b1) & (distStream_3_full_n == 1'b0)) | ((ap_predicate_op101_write_state8 == 1'b1) & (distStream_4_full_n == 1'b0)) | ((ap_predicate_op99_write_state8 == 1'b1) & (distStream_5_full_n == 1'b0)) | ((ap_predicate_op97_write_state8 == 1'b1) & (distStream_6_full_n == 1'b0)) | ((distStream_0_full_n == 1'b0) & (ap_predicate_op109_write_state8 == 1'b1)));
end

always @ (*) begin
    ap_predicate_op101_write_state8 = ((trunc_ln214_reg_741 == 3'd4) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op103_write_state8 = ((trunc_ln214_reg_741 == 3'd3) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op105_write_state8 = ((trunc_ln214_reg_741 == 3'd2) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op107_write_state8 = ((trunc_ln214_reg_741 == 3'd1) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op109_write_state8 = ((trunc_ln214_reg_741 == 3'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op111_write_state8 = ((trunc_ln214_reg_741 == 3'd7) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op142_write_state13 = ((empty_fu_140 == 4'd6) & (icmp_ln253_fu_600_p2 == 1'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op144_write_state13 = ((empty_fu_140 == 4'd5) & (icmp_ln253_fu_600_p2 == 1'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op146_write_state13 = ((empty_fu_140 == 4'd4) & (icmp_ln253_fu_600_p2 == 1'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op148_write_state13 = ((empty_fu_140 == 4'd3) & (icmp_ln253_fu_600_p2 == 1'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op150_write_state13 = ((empty_fu_140 == 4'd2) & (icmp_ln253_fu_600_p2 == 1'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op152_write_state13 = ((empty_fu_140 == 4'd1) & (icmp_ln253_fu_600_p2 == 1'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op154_write_state13 = ((empty_fu_140 == 4'd0) & (icmp_ln253_fu_600_p2 == 1'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op156_write_state13 = (~(empty_fu_140 == 4'd6) & ~(empty_fu_140 == 4'd5) & ~(empty_fu_140 == 4'd4) & ~(empty_fu_140 == 4'd3) & ~(empty_fu_140 == 4'd2) & ~(empty_fu_140 == 4'd1) & ~(empty_fu_140 == 4'd0) & (icmp_ln253_fu_600_p2 == 1'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op158_read_state13 = ((icmp_ln253_fu_600_p2 == 1'd1) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op163_read_state13 = ((icmp_ln258_fu_606_p2 == 1'd0) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_endBlck_out == 1'd1));
end

always @ (*) begin
    ap_predicate_op166_write_state14 = ((reg_468 == 4'd6) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0));
end

always @ (*) begin
    ap_predicate_op168_write_state14 = ((reg_468 == 4'd5) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0));
end

always @ (*) begin
    ap_predicate_op170_write_state14 = ((reg_468 == 4'd4) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0));
end

always @ (*) begin
    ap_predicate_op172_write_state14 = ((reg_468 == 4'd3) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0));
end

always @ (*) begin
    ap_predicate_op174_write_state14 = ((reg_468 == 4'd2) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0));
end

always @ (*) begin
    ap_predicate_op176_write_state14 = ((reg_468 == 4'd1) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0));
end

always @ (*) begin
    ap_predicate_op178_write_state14 = ((reg_468 == 4'd0) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0));
end

always @ (*) begin
    ap_predicate_op180_write_state14 = (~(reg_468 == 4'd6) & ~(reg_468 == 4'd5) & ~(reg_468 == 4'd4) & ~(reg_468 == 4'd3) & ~(reg_468 == 4'd2) & ~(reg_468 == 4'd1) & ~(reg_468 == 4'd0) & (icmp_ln253_reg_796 == 1'd1) & (endBlck_loc_load_reg_789 == 1'd0));
end

always @ (*) begin
    ap_predicate_op187_write_state14 = ((icmp_ln258_reg_800 == 1'd0) & (reg_468 == 4'd6) & (endBlck_loc_load_reg_789 == 1'd1));
end

always @ (*) begin
    ap_predicate_op189_write_state14 = ((icmp_ln258_reg_800 == 1'd0) & (reg_468 == 4'd5) & (endBlck_loc_load_reg_789 == 1'd1));
end

always @ (*) begin
    ap_predicate_op191_write_state14 = ((icmp_ln258_reg_800 == 1'd0) & (reg_468 == 4'd4) & (endBlck_loc_load_reg_789 == 1'd1));
end

always @ (*) begin
    ap_predicate_op193_write_state14 = ((icmp_ln258_reg_800 == 1'd0) & (reg_468 == 4'd3) & (endBlck_loc_load_reg_789 == 1'd1));
end

always @ (*) begin
    ap_predicate_op195_write_state14 = ((icmp_ln258_reg_800 == 1'd0) & (reg_468 == 4'd2) & (endBlck_loc_load_reg_789 == 1'd1));
end

always @ (*) begin
    ap_predicate_op197_write_state14 = ((icmp_ln258_reg_800 == 1'd0) & (reg_468 == 4'd1) & (endBlck_loc_load_reg_789 == 1'd1));
end

always @ (*) begin
    ap_predicate_op199_write_state14 = ((icmp_ln258_reg_800 == 1'd0) & (reg_468 == 4'd0) & (endBlck_loc_load_reg_789 == 1'd1));
end

always @ (*) begin
    ap_predicate_op201_write_state14 = (~(reg_468 == 4'd6) & ~(reg_468 == 4'd5) & ~(reg_468 == 4'd4) & ~(reg_468 == 4'd3) & ~(reg_468 == 4'd2) & ~(reg_468 == 4'd1) & ~(reg_468 == 4'd0) & (icmp_ln258_reg_800 == 1'd0) & (endBlck_loc_load_reg_789 == 1'd1));
end

always @ (*) begin
    ap_predicate_op97_write_state8 = ((trunc_ln214_reg_741 == 3'd6) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0));
end

always @ (*) begin
    ap_predicate_op99_write_state8 = ((trunc_ln214_reg_741 == 3'd5) & (grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign blckEosStream_din = blckEosStream_din_local;

assign blckEosStream_write = blckEosStream_write_local;

assign coreIdxStream_din = core;

assign coreIdxStream_write = coreIdxStream_write_local;

assign empty_137_fu_520_p2 = ((trunc_ln214_fu_515_p1 == 3'd7) ? 1'b1 : 1'b0);

assign empty_141_fu_581_p2 = ((empty_fu_140 == 4'd7) ? 1'b1 : 1'b0);

assign fileSizeStream_din = select_ln268_fu_627_p3;

assign fileSizeStream_write = fileSizeStream_write_local;

assign grp_fu_443_p2 = (empty_fu_140 + 4'd1);

assign grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_start = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_ap_start_reg;

assign grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_start = grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_ap_start_reg;

assign grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_start = grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_ap_start_reg;

assign grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_start = grp_multicoreDistributor_Pipeline_ip_terminate_data_fu_398_ap_start_reg;

assign grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_start = grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_ap_start_reg;

assign icmp_ln253_fu_600_p2 = ((reg_449 == grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_writeSize_2_out) ? 1'b1 : 1'b0);

assign icmp_ln258_fu_606_p2 = ((grp_multicoreDistributor_Pipeline_VITIS_LOOP_240_2_fu_354_strdCntr_3_out == 16'd0) ? 1'b1 : 1'b0);

assign last_2_loc_load_load_fu_545_p1 = grp_multicoreDistributor_Pipeline_VITIS_LOOP_217_1_fu_322_last_2_out;

assign select_ln268_fu_627_p3 = ((targetBlock_reg_804[0:0] == 1'b1) ? reg_449 : writeSize_3_loc_fu_144);

assign start_out = real_start;

assign strdSizeStream_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdSizeStream_din;

assign strdStream_din = grp_multicoreDistributor_Pipeline_VITIS_LOOP_263_3_fu_384_strdStream_din;

assign trunc_ln195_fu_577_p1 = readSize_1_fu_128[15:0];

assign trunc_ln214_fu_515_p1 = core[2:0];

assign zext_ln203_fu_506_p1 = grp_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_Pipeline_init_loop_fu_313_readSize_out;

assign zext_ln214_fu_527_p1 = trunc_ln214_reg_741;

always @ (posedge ap_clk) begin
    zext_ln214_reg_752[3] <= 1'b0;
end

endmodule //gzipcMulticoreStreaming_multicoreDistributor_unsigned_int_64_4_8_4096_64_0_s
